# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qgoferpix',
                'doc_host': 'https://qgofer.github.io',
                'git_url': 'https://github.com/qgofer/qgoferpix',
                'lib_path': 'qgoferpix'},
  'syms': {'qgoferpix.core': {}}}
