<<<<<<< HEAD
# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qgoferpix',
                'doc_host': 'https://qgofer.github.io',
                'git_url': 'https://github.com/qgofer/qgoferpix',
                'lib_path': 'qgoferpix'},
  'syms': {'qgoferpix.core': {'qgoferpix.core.foo': ('core.html#foo', 'qgoferpix/core.py')}}}
=======
# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qgoferpix',
                'doc_host': 'https://qgofer.github.io',
                'git_url': 'https://github.com/qgofer/qgoferpix',
                'lib_path': 'qgoferpix'},
  'syms': {'qgoferpix.core': {'qgoferpix.core.foo': ('core.html#foo', 'qgoferpix/core.py')}}}
>>>>>>> ba2f493e2dbcb14773f7d6a29bd4ba79dc54bf5a
