<<<<<<< HEAD
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
def foo(): pass
=======
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
def foo(): pass
>>>>>>> ba2f493e2dbcb14773f7d6a29bd4ba79dc54bf5a
